### PR TITLE
Slice oversized key to 32 bytes and Use AES-256-GCM instead of CBC

### LINKED ISSUE #20: No encryption when the secret is too long
When the secret exceeds 32 bytes, the data is not encrypted.

## Steps to reproduce
```bash
# on admin
./admin -c 1.1.1.1:1111 -s abcdefghijklmnopqrstuvwxyz0123456789

# on agent
./agent -l 1111 -s abcdefghijklmnopqrstuvwxyz0123456789
```

## Reason
- In `protocol/protocol.go`, the error returned by `crypto.KeyPadding` is ignored
- In `KeyPadding` (`crypto/aes.go`), when the key is too long, it is returned as `nil` with an error
- In `AESEncrypt` (`crypto/aes.go`), when the key is `nil`, it does not perform encryption

## Solution
As few users would use such kind of key, instead of handling this error I think it's better to just slice the key into 32 bytes. Besides, it's recommended to use stronger encryption mode like **AES-256-GCM** rather than the insecure CBC mode.

I'm working on resolving this issue before creating a pull request.

### PR DESCRIPTION
**Pull request by SignorMercurio**
This should close #20 .

Due to my markdown formatter, the README format has also changed. Feel free to ask me to discard these changes if you wish.

### CODE REVIEW

**Comment by ph4ntonn** [comment]
Hi~Really thanks for you pr
I have made few changes on your pr, would you plz check if the pr's option ```Allow edits from maintainers``` activated?
If not,plz activate it,thx~

**Comment by ph4ntonn** [comment]
Hi,really thanks for you pr
I have made few changes on your pr, would you plz check if the pr's option Allow edits from maintainers activated?
If not,plz activate it,thx  :D

**Comment by SignorMercurio** [comment]
> Hi,really thanks for you pr I have made few changes on your pr, would you plz check if the pr's option `Allow edits from maintainers` activated? If not,plz activate it,thx :D

✅  Already activated

**Comment by ph4ntonn** [comment]
Merged! And i will update release ASAP 
Thanks again! :D 
BTW，Happy National day,ENJOY!

**Pull request merged**
